### ISSUE TITLE
Cannot run npm start

### ISSUE THREAD

**Issue by tthdvd** [Qolzam/react-social-network#107]
**Describe the bug**
When i try to run npm start failed to compile. I completed the installation steps using npm not yarn regarding to: https://medium.com/red-gold/create-social-network-by-react-js-fe60010a32e6

**To Reproduce**
1. Go to root folder
2. run npm start

**Additional context**
The error:
```
react-social-network/node_modules/connected-react-router/index.d.ts
(4,12): Module '"../@types/react-redux"' has no exported member 'ReactReduxContextValue'.
```

**Comment by thierry-tct** [comment]
Hello, I had the same issue.
This was fixed when I upgraded @types/react-redux to last version with
```
npm install --save @types/react-redux@7.0.1
```

**Comment by kapilip** [comment]
@tthdvd You can fix it using yarn instead of npm i.e. use yarn install followed by yarn start. Actually npm start uses typescript 3.3.333 which breaks the older version of react-redux.
You can also upgrade the react-redux to 7.0.1 as mentioned by @thierry-tct to resolve this issue.

**Comment by tthdvd** [comment]
yarn install solved the problem

**Comment by Qolzam** [comment]
The problem is solved so I close here. However about the problem with npm I will update with version 0.7.0  #109
