### ISSUE TITLE
Help! Error "has no exported member 'ReactReduxContextValue'"

### ISSUE THREAD

**Issue by EHRdev** [Qolzam/react-social-network#110]
I followed all the steps and I do not know what else to do

![abc](https://user-images.githubusercontent.com/40396000/54907975-740f1e00-4eac-11e9-8d09-0b37ee5d6566.png)

![abc2](https://user-images.githubusercontent.com/40396000/54908013-8b4e0b80-4eac-11e9-94eb-de4d942b9787.png)

**Comment by Qolzam** [comment]
Issue has been resolved. Please let me know if any issue. Thanks!

**Comment by EHRdev** [comment]
> Issue has been resolved. Please let me know if any issue. Thanks!

Amazing! Thank you.
