### ISSUE TITLE
[Enhancement] Upload profile image in background

### ISSUE THREAD

**Issue by Qolzam** [Qolzam/react-social-network#117]
@Qolzam Thanks for your appreciate, as we discuss above there is need to enhance at the profile image uploading :
1. We can use the direct image at image upload without waiting for the response and update it in background
To generate issue follow :  goto profile -> select edit profile -> select photo upload -> then input the photo -> here we can use the direct image uploading in same manner  as image uploads at the time of album creation instead of showing loading text with red background.
Image uploading screen at profile:
![Screenshot 2019-05-27 at 6 55 37 PM](https://user-images.githubusercontent.com/47344994/58424205-91cb5000-80b4-11e9-840f-9e545d2391d6.png)
Image uploading screen at Album:
![Screenshot 2019-05-27 at 6 58 47 PM](https://user-images.githubusercontent.com/47344994/58424325-cb9c5680-80b4-11e9-8d67-d2ddb761d256.png)
 Also we discuss about size of profile image at time of uploading screen:
2. Also, the uploaded image size is not the same as the need to correct them
please look at the image uploaded and upload image button, both are with  different frame. It will look pity well if they have same size.

_Originally posted by @Abhiranjanchaurasia in https://github.com/red-gold/react-social-network/issues/116#issuecomment-496221049_

**Comment by Abhiranjanchaurasia** [comment]
@Qolzam we have created the  enhancement regarding the profile image uploading :
1. We can use the direct image at image upload without waiting for the response and update it in background
2. The uploaded image size
both above are enhanced now

**Comment by Qolzam** [comment]
@Abhiranjanchaurasia, it's great. However for uploading in background, is there any place or notification to tell user not to close the browser for upload progress.

I would appreciate if you pull request the enhancement, so I can review what you have done.

Thanks a lot! 👍
