### ISSUE TITLE
[Enhancement] Selecting my account button doesn't showing the edit profile

### ISSUE THREAD

**Issue by Qolzam** [Qolzam/react-social-network#120]
@Qolzam we have also discuss about the selecting the my account doen't showing the edit profile, it may be pity well if it shows the edit profile.
 My account selectable but not working, we can fix by showing the account info with editable button activation
![Screenshot 2019-05-27 at 8 03 34 PM](https://user-images.githubusercontent.com/47344994/58426616-a7dc0f00-80ba-11e9-903d-a890d9aa22f6.png)

_Originally posted by @Abhiranjanchaurasia in https://github.com/red-gold/react-social-network/issues/116#issuecomment-496232760_

**Comment by Abhiranjanchaurasia** [comment]
@Qolzam we started working on these updates & will be completing it by EOD tomorrow.

**Comment by Abhiranjanchaurasia** [comment]
@Qolzam as we have discussed the feature 1. My account selectable but not working, we can fix by showing the account info with editable button activation has been implemented, please make sure and merge the code.

**Comment by Qolzam** [comment]
Hello @Abhiranjanchaurasia , I appreciate your contribution. Feel free for pull request.

Thanks!
