### ISSUE TITLE
why telar social?

### ISSUE THREAD

**Issue by bayareabear** [Qolzam/react-social-network#127]
react social is very easy to set up and deploy. In contrast telar social require so many ingredients to set up. I spent 1.5 days but couldn't figure out how to set up Open Faas. What's the point?

**Comment by Qolzam** [comment]
@bayareabear , Thank you for your feedback. I agree with you Telar Social setup is more difficult than React Social Network. 
Telar Social mostly focus on building a highly salable and high performance cloud native app that you can run on any cloud (public/private/on-premise). But React Social Network only running on Firebase with nodeJs(Telar Social written in Go). 
Telar Social has a flexible infrastructure working with new technologies like Kubernetes. I encourage you to take a look at [Apply Domain-Driven Design to Microservices architecture using OpenFaas](https://medium.com/red-gold/telar-social-media-architecture-using-domain-driven-design-for-microservices-319c514199e4)
The good new is, I am working to make it like one-click setup. 
Please let me know what was the difficulty to setup OpenFaaS.
The feedback is so valuable to me. Please let me know if you have any difficulty, so for coming days I can apply more improvements.

**Comment by bayareabear** [comment]
Hi Amir, thanks for the reply. I can see the migration is for a long term thinking. I am curious what motivates you to this change? 
I'll continue to try out telar social and compile a list of points for improvements. Again, appreciate all the detailed explanation. If possible, I can also potentially contribute to your repo.

**Comment by Qolzam** [comment]
Hi @bayareabear, 

There are some ideas I have in my mind to implement on this project like AI solutions, blockchain and get to high scalability with lower cost in infrastructure that I could not achieve using Firebase. And further idea is lunching a Social Network Cloud Provider.
I appreciate and consider carefully all your points. You are very welcome for any contribution. Your help can make the achievement faster. Let's continue talking in [chat](https://redgold.zulipchat.com/#narrow/stream/224949-contributors) about the contribution and how we can help each other.

**Comment by bayareabear** [comment]
One thing that blocks me is the OpenFaaS cloud. I tried to apply for access but never got any response

**Comment by Qolzam** [comment]
@bayareabear, Can you tell me when you registered for OpenFaaS cloud?
I will try contact to OpenFaaS people.

**Comment by alexellis** [comment]
Hi George, my records show that you applied for the community cluster only 2 working days ago on 26th Feb. The Community Cluster is a completely free resource and all sign-ups have to be verified manually for spam and misuse. You should hear from me within a few days.

Feel free to join OpenFaaS Slack.

Alex

**Comment by MonteLogic** [comment]
I use this codebase to check how to use large scale redux with TypeScript. This codebase is valued. I like many developers have little to no interest in golang. I will attempt to maintain this boilerplate if no other developers are interested.

**Comment by Qolzam** [comment]
Thanks @dchavours for your interest :) 
Indeed you are able to develop/add feature on the backend  in any [language](https://docs.openfaas.com/cli/templates/) you are interested in. 
Anyway any contribution is very welcome 👍

**Comment by Qolzam** [comment]
@bayareabear I have just released [Telar CLI](https://github.com/Qolzam/telar-cli) automated setup!
