### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by imatulkt** [Qolzam/react-social-network#129]
When I am trying to deploy it on firebase, I am getting ERROR : 400, this is not available for Cloudstore firebase project in datamode. I am unable to deploy it over firebase by firebase deploy command

Expected behavior :
After typing firebase deploy command, the project should be deployed on firebase.

Desktop 
 - OS: Windows 10
 - Browser : Chrome
 
![error](https://user-images.githubusercontent.com/52238085/76620005-40605480-6552-11ea-8f02-aa262f8cb1bb.PNG)

**Comment by Qolzam** [comment]
Thank you @imatulkt for your report.  I have done some changes. Can you try and let me know if there is any issue?

Also have you tried a new [cloud native version of social network](https://telar.press)?

**Comment by Qolzam** [comment]
I will close this for now but feel free to reopen if you have any issue.
Thanks again!
