### ISSUE TITLE
Is follow user feature working?

### ISSUE THREAD

**Issue by bayareabear** [Qolzam/react-social-network#131]
When I click "FOLLOW" in the FindPeople component, I see error:

TypeError: Cannot read property '0' of undefined
UserBoxComponent._this.onFollowUser
src/components/userBox/UserBoxComponent.tsx:182
  179 | }
  180 | if (!isFollowed) {
  181 |   debugger
> 182 |   followUser!(followingCircle![0], { avatar, userId, fullName })
  183 | } else {
  184 |   this.onRequestOpenAddCircle()
  185 | }

Also it would be good to add some documentation on what is UserTie and Circle; And what is the difference between FollowingComponent and YourCirclesComponent?

Thank you!

**Comment by Qolzam** [comment]
Hi @bayareabear , I appreciate your bug report and recommendation 🙂. 
However as I already wrote in [README](https://github.com/red-gold/react-social-network/blob/next/README.md) file on the repository ...
![image](https://user-images.githubusercontent.com/8446573/97767313-f9a98400-1b4d-11eb-90b4-9d9394861c59.png)
I am working on a [Telar Social UI (new version)](https://github.com/red-gold/ts-ui) which fixed these issues. But this version is written in [Golang](https://golang.org/) and working on [Kubernetes](https://kubernetes.io/) which is for the projects in huge scale in production.

Here is the good news 🤩. I am working on TypeScript/JavaScript platform of [Telar Social](https://telar.dev/) which supports more platforms (not only [Kubernetes](https://kubernetes.io/)) like [Firebase](https://firebase.google.com/), [Vercel](https://vercel.com/) and [Netlify](https://vercel.com/). Also in new version we have [Next.js version of UI](https://github.com/Qolzam/ts-next) which supports features like [SSR](https://medium.com/better-programming/next-js-react-server-side-rendering-done-right-f9700078a3b6) and [PWA](https://medium.com/@deepusnath/4-points-to-keep-in-mind-before-introducing-progressive-web-apps-pwa-to-your-team-8dc66bcf6011).

You can follow the project on [Slack](https://docs.google.com/forms/d/e/1FAIpQLSdkwt5pxmyCZQO0AmyAghBOdA-XBG298Pfm5Dw1xjNGaGeCYQ/viewform) or [my twitter](https://twitter.com/qolzam) to get notification about project release 🛎.
