### ISSUE TITLE
Can't see followers

### ISSUE THREAD

**Issue by QuantumInformation** [Qolzam/react-social-network#19]
### Steps

Follow a user:

![image](https://user-images.githubusercontent.com/216566/31375740-71fcbb4a-ad9a-11e7-8e64-9f627807ebff.png)

On the followed account you can't see the follower

![image](https://user-images.githubusercontent.com/216566/31375810-a9b7a50e-ad9a-11e7-967f-8ec1db25f344.png)

**Comment by Qolzam** [comment]
Could you please give me the error from console browser and if it is your local?

**Comment by QuantumInformation** [comment]
Its on local, if I click follow I get this error:

![image](https://user-images.githubusercontent.com/216566/31380266-bbfa95a6-ada8-11e7-99a5-0b74103619a3.png)

**Comment by Qolzam** [comment]
Thanks! I hope this change work now.

**Comment by QuantumInformation** [comment]
Thx 4 quick fix
