### ISSUE TITLE
Feedback button doesn't do anything

### ISSUE THREAD

**Issue by QuantumInformation** [Qolzam/react-social-network#20]
![image](https://user-images.githubusercontent.com/216566/31380734-169eba68-adaa-11e7-9107-f9faa7996894.png)

**Comment by Qolzam** [comment]
I have no idea for feed back yet. I would be happy if you have any idea, share with me.

**Comment by QuantumInformation** [comment]
I don't really see the point of it atm, but it could just be a form that a user could submit text, and then there is a google cloud function to send an email to the developer. I guess you could have a json config file that the cloud function reads to get the developer email.

One disadvantage of this is that you are tying yourself more to firebase, but I guess the app already is pretty tied to firebases given the firebase queries.

**Comment by Qolzam** [comment]
Merged.
