### ISSUE TITLE
[Question] Rational for circles

### ISSUE THREAD

**Issue by QuantumInformation** [Qolzam/react-social-network#24]
Given that only google has this concept of circles, I'm wondering if circles is the best approach.

Instead of organising contacts under circles, perhaps it would be better to store a users contacts/followings in a flat structure. If further organisation would be needed later the user could tag the contact via a new table, for example usertags > user > Tag1 > [userID1,userID2]

Mind you this might make it harder to query to find all users under the same tag for all users.

**Comment by toyeebgodo** [comment]
As someone who is unfamiliar with Google+ let alone the circles concept, I found the follow implementation utterly confusing. I did  not understand what I was supposed to do to follow someone. Is it harder to implement a follow feature that just enables folks to hit the follow button? @Qolzam , I am a huge fan of your wonderful work so please pardon my concern. I humbly surmise that the simple "hit follow button" of Instagram and Twitter might be easier for lazy and unsophisticated users like me. Thanks, man.

**Comment by Qolzam** [comment]
@QuantumInformation the thing you mentioned in my idea is like a graph with label. 
- `userID-follow->userID2` or
- `userID2-follow->userID1` or
- `userID2<-bilateral->userID1`. 
In other word as you said it could be in database like : 
- `usertags > user > follow > [userID1,userID2]` or
- `usertags > user > follow > [userID2,userID2]` or
- `usertags > user > bilateral > [userID2,userID2]`
We also can do circle approach for the users want to have a group to manage permission and notifications as a group : 
- `usertags > user > follow > [userID1,userID2, GroupID1]` or
- `usertags > user > follow > [userID2,userID2, GroupID2]` or
- `usertags > user > bilateral > [userID2,userID2, GroupID2, GroupID1]`

**Comment by Qolzam** [comment]
Merged.
