### ISSUE TITLE
Better sourcemaps

### ISSUE THREAD

**Issue by QuantumInformation** [Qolzam/react-social-network#27]
In chrome debugging isn't so good. I'll look at various sourcemap options.

Black and white source, and hovering over variables produces no output.

![image](https://user-images.githubusercontent.com/216566/31558887-947d694a-b046-11e7-930f-69caf9c58216.png)

**Comment by QuantumInformation** [comment]
I tried various ones but no improvement.

https://webpack.js.org/configuration/devtool/

Perhaps https://github.com/wmonk/create-react-app-typescript would have the silver bullet.

**Comment by Qolzam** [comment]
Merged.
