### ISSUE TITLE
Question: auth reference vs auth() execution

### ISSUE THREAD

**Issue by pronevich** [Qolzam/react-social-network#28]
Maybe you know what the difference between this two examples:
```js
export let firebaseAuth = firebase.auth
// and
export let firebaseAuth = firebase.auth() // instead every time call firebaseAuth() just firebaseAuth.someMethod/Property
```
https://github.com/Qolzam/react-social-network/blob/a40c18d2533b78554cff36044948c3b6044c7c3a/app/firebase/index.js#L22

**Comment by Qolzam** [comment]
It's javascript stuff not about this project. And you have the answer in the comment. `Instead every time call firebaseAuth() just firebaseAuth.someMethod/Property`.

**Comment by pronevich** [comment]
@Qolzam I remarked that you doing opposite: calling firebaseAuth() every time. So I assumed that evaluation has some reason, like every time firebase auth api check something

**Comment by Qolzam** [comment]
Thanks you for supporting. It will be changed in the next version.

**Comment by Qolzam** [comment]
Merged in next version.
