### ISSUE TITLE
[BUG] Real time notifications not work (as in live example greensocial.herokuapp.com)

### ISSUE THREAD

**Issue by sevastosm** [Qolzam/react-social-network#30]
### Steps
1 Running the app on my local machine
2 Opening two different browsers ,
3 Log in with a differed user account on each browser
### Expected Result
If a user votes a post the account in that posted must get a notification in the broswer.  
### Actual Result
I have to refresh the page to get notification from other folowers
### Version
x.y.z

### Testcase

**Comment by Qolzam** [comment]
Thank you for reporting 👍 . Moving getNotifications to the service layer and return promise from `on()` observable method of firebase can't call resolve() method for the next change. I used a callback function to solve it but following project principles it is anti pattern. So I let it open to find a better way.

**Comment by Qolzam** [comment]
Solved by implementing [redux-saga channel](https://redux-saga.js.org/docs/advanced/Channels.html) here #48 .
