### ISSUE TITLE
A user is receiving notifications for actions they carried out - the user ended up receiving my notifications

### ISSUE THREAD

**Issue by toyeebgodo** [Qolzam/react-social-network#31]
### Steps
- My team mate, Ayomide and I created accounts to demo the app

- Ayomide then

1 Followed me
2 Commented on my post
3 Voted on my post
              
### Expected Result

There shouldn't have been any expected result because those are normal interactions by a user.

### Actual Result

Ayomide surprisingly received three notifications that read:

1 Ayomide Otunba follow you

2 Ayomide Otunba add comment on your post

3 Ayomide Otunba Vote on your post

What this means is that, Ayomide Otunba received three notifications that were supposed to have been mine. She was not supposed to have received any of the notifications above for actions that she carried out herself. I was supposed to have been the one receiving the notifications. 
### Version
x.y.z

### Testcase

**Comment by Qolzam** [comment]
Thanks for reporting. I've followed your steps as a new user in a new repository of `master`, and I traced the procedure too. However, everything is going well. Please be sure you are using updated branch.

**Comment by toyeebgodo** [comment]
@Qolzam , thanks for your quick reply. The issue occurred several times while I was using the demo http://greensocial.herokuapp.com . I have not set the app up on firebase, yet.

**Comment by Qolzam** [comment]
Thanks. I have just synced [Demo](http://greensocial.herokuapp.com) with `master` repository.
