### ISSUE TITLE
Tagline not visible on Profile page

### ISSUE THREAD

**Issue by AyomideOtunba** [Qolzam/react-social-network#32]
### Steps
1 While running a demo of the app on http://greensocial.herokuapp.com
2 I clicked on the edit profile button
3 I added a few lines about me to the Tagline
### Expected Result
I expected that my tagline will show up on my profile upon updating it. 
Can you educate me on the purpose of the tagline as I thought it was meant to be like the bio feature on Instagram 
### Actual Result
Nothing showed up on my profile. 
### Version
x.y.z

### Testcase

**Comment by Qolzam** [comment]
Tag line has been add to profile under the full name of user. Thank you for your consideration.

**Comment by toyeebgodo** [comment]
Thank you for your kindness.
