### ISSUE TITLE
Firebase picture upload

### ISSUE THREAD

**Issue by toyeebgodo** [Qolzam/react-social-network#33]
### Steps

I just finished installing and setting up the app through Firebase

I tried posting something

### Expected Result

I expected to be able to upload a picture from my computer to my newsfeed and avatar.

### Actual Result

I was able to post words to the newsfeed, however I was not able to upload any picture to neither my newsfeed nor my avatar. Please help.

### Version
x.y.z

### Testcase

**Comment by Qolzam** [comment]
Thanks for reporting 👍  problem has been solved.
