### ISSUE TITLE
Blank screen upon running web server

### ISSUE THREAD

**Issue by toyeebgodo** [Qolzam/react-social-network#34]
### Steps

I git cloned the master in order to see the effects of your last commit relating to picture upload
Then proceeded to install and setup app through firebase
I ran web server

### Expected Result

I expected to see the create account / login page

### Actual Result

I did not see the create account / login page. I only saw a blank page. Please find attached printed screen below

### Version
x.y.z

### Testcase
![react-social-network-bug](https://user-images.githubusercontent.com/23325937/32137237-d94f5a28-bc13-11e7-9ecf-f10a46b4e6ef.png)

**Comment by Qolzam** [comment]
Could you please send me the error in [console](https://developers.google.com/web/tools/chrome-devtools/console/). And please check if you created config file according installing instruction.

**Comment by toyeebgodo** [comment]
@Qolzam, please find console error below. Thank you as always for your kind attention to this issue.
![myhustle-ts-error](https://user-images.githubusercontent.com/23325937/32140315-7e9723aa-bc5d-11e7-8ab1-304d0479a1ae.png)

**Comment by Qolzam** [comment]
Error shows you can't connect to the `Firebase`. Please check your Firebase configuration file according [installation instruction](https://github.com/Qolzam/react-social-network#installing).

**Comment by toyeebgodo** [comment]
Thanks for your swift response.
