### ISSUE TITLE
[Feature request] Change Password screen

### ISSUE THREAD

**Issue by QuantumInformation** [Qolzam/react-social-network#36]
It would be great for users to reset their password. I think it would be great to have this feature.

If you want I can do this for you for the client. Maybe you could do the firebase part?

**Comment by QuantumInformation** [comment]
this could be done in a new branch?

**Comment by Qolzam** [comment]
Thanks. In the new version I have added both reset password and User confirmation #23. I'm trying to make time to release this update.

**Comment by Qolzam** [comment]
Merged.
