### ISSUE TITLE
Image upload help needed

### ISSUE THREAD

**Issue by toyeebgodo** [Qolzam/react-social-network#37]
### Steps

I tried uploading a profile image after running the app locally

### Expected Result

Image should be uploaded

### Actual Result

Image did not upload . Please teach me what I am missing. Does this app need to be connected to a Google cloud storage object for image upload to be implemented or it needs another server-less backend like AWS S3 bucket? Please guide me on how to go about it.

### Version
![react-social-network image not uploading](https://user-images.githubusercontent.com/23325937/32991288-aec4850e-cd38-11e7-88e6-b37c070d1992.png)

x.y.z

### Testcase

**Comment by Qolzam** [comment]
I have checked both [Green Social](https://greensocial.herokuapp.com/) and my local repository with the last update but I haven't got this error. Please check if you are in the last commit of [react-social-network](https://github.com/Qolzam/react-social-network).

**Comment by toyeebgodo** [comment]
I have fixed the upload issue. I had to go to my project in the Firebase console. Clicked on "storage", then clicked on "Get started", and finally clicked on "Got it"  from the the security rules popup window. It then finally worked. Thanks for your patience and continued help.
