### ISSUE TITLE
UserAvatar component errors

### ISSUE THREAD

**Issue by toyeebgodo** [Qolzam/react-social-network#38]
![typeerror](https://user-images.githubusercontent.com/23325937/32994911-798f4cc2-cd6d-11e7-8bc4-196d6510cfd6.png)
### Steps
I was able to successfully create an account after my setting up Firebase config.
My partner tried to create an account and it resulted in a blank screen with the following errors.
### Expected Result
![useravatar error](https://user-images.githubusercontent.com/23325937/32994758-35566bc2-cd6c-11e7-872f-1cbd912bd988.png)

### Version
x.y.z

### Testcase

**Comment by Qolzam** [comment]
I'm not sure which version of repository you are using, because when user register I fill the data. By the way I solved this problem which the data can be null. I hope it helps 5477197.

**Comment by toyeebgodo** [comment]
Thank you as always.
