### ISSUE TITLE
Notifications popover not working properly on mobile

### ISSUE THREAD

**Issue by toyeebgodo** [Qolzam/react-social-network#39]
### Steps

I was testing the demo app on my iphone

I decided to view my notifications through my iphone

### Expected Result

I expected to
![notifications not showing](https://user-images.githubusercontent.com/23325937/33127510-082fd86c-cf89-11e7-81cf-35887211f9c7.png)
 be able to view all my notifications through the popover

### Actual Result

I could only see one notification out of the 8 notifications I had as you can see evidenced in the screenshot attached. The popover isn't showing my other 7 notifications. Please help, thank you as always for your wonderful work.

### Version
x.y.z

### Testcase

**Comment by Qolzam** [comment]
Resolved in the `next version` and `material-ui` update.
