### ISSUE TITLE
Question: How's database structure and security rules?

### ISSUE THREAD

**Issue by metalray7mr** [Qolzam/react-social-network#44]

**Comment by Qolzam** [comment]
@metalray7mr Thank you for your question. As your question talk generally, could you please give me more detail that how I can help you?

**Comment by metalray7mr** [comment]
just wanted to  know more about  how to manage security rules in such a complex project. Can you make rules public?

**Comment by Qolzam** [comment]
This issue relate to #22 which you can follow any update.
