### ISSUE TITLE
Debugging with vs code on Windows machine 

### ISSUE THREAD

**Issue by sevastosm** [Qolzam/react-social-network#45]
### Steps
Try to debug the application with Debugger for Chrome plugin in vs code
### Actual Result
Break points ignored
### Version
x.y.z

### Testcase

**Comment by QuantumInformation** [comment]
Not really related to this lib

**Comment by Qolzam** [comment]
@sevastosm Thanks you for your consideration. Could you please give us more details how it could be relate to this project and if this feature has any benefit for this project? Thanks again!

**Comment by sevastosm** [comment]
The problem was the same as the #27 issue thanks again @Qolzam
