### ISSUE TITLE
[BUG] Provider icons icons not appear in login page browsing with Firefox

### ISSUE THREAD

**Issue by sevastosm** [Qolzam/react-social-network#46]
### Steps
Loading login page with Firefox
### Expected Result
To see icons fro googe + , github, facebook, etc
### Actual Result
icons not appear
### Version
x.y.z

### Testcase

**Comment by Qolzam** [comment]
@sevastosm I appreciate your support. [It is not valid for data URIs to contain # characters](https://stackoverflow.com/questions/30676125/svg-as-data-uri-triggers-xml-parsing-error-in-firefox). It's resolved 👍
