### ISSUE TITLE
[Bug] Get compile error on npm start

### ISSUE THREAD

**Issue by upwardstudios** [Qolzam/react-social-network#50]
react-social-network-next/src/api/FileAPI.ts
(39,5): Type '(this: FileReader, readerEvent: FileReaderEvent) => void' is not assignable to type '((this: FileReader, ev: ProgressEvent) => any) | null'.
  Type '(this: FileReader, readerEvent: FileReaderEvent) => void' is not assignable to type '(this: FileReader, ev: ProgressEvent) => any'.
    Types of parameters 'readerEvent' and 'ev' are incompatible.
      Type 'ProgressEvent' is not assignable to type 'FileReaderEvent'.
        Property 'getMessage' is missing in type 'ProgressEvent'.

**Comment by Qolzam** [comment]
Thanks for report but I really can't understand what you mean by that. Is it compile error? What is the steps I can reproduce this error?

**Comment by upwardstudios** [comment]
Just happens on the last step when I run non start, browser opens up and shows this along with the console

**Comment by Qolzam** [comment]
I have done 3 steps: 

``` bash
git clone git@github.com:Qolzam/react-social-network.git
yarn install or (npm install)
yarn start or (npm start) 
```

It's compiling successfully and also I created a post with photo. Everything seems well.
Please let me know how can I help you more.

**Comment by Qolzam** [comment]
Issue with `npm install` has been resolved. I'm going to close this issue.

**Comment by rajabhinav99** [comment]
Cannot find module './webpack.config'
