### ISSUE TITLE
Exception after latest build

### ISSUE THREAD

**Issue by upwardstudios** [Qolzam/react-social-network#51]
on npm start exception thrown:

Failed to compile
/react-social-network-next/src/containers/login/LoginComponent.tsx
(261,88): Argument of type '(theme: any) => { textField: { minWidth: number; marginTop: number; }; contain: { margin: string;...' is not assignable to parameter of type 'Record<"link" | "contain" | "paper" | "textField" | "bottomPaper", CSSProperties> | StyleRulesCal...'.
  Type '(theme: any) => { textField: { minWidth: number; marginTop: number; }; contain: { margin: string;...' is not assignable to type 'StyleRulesCallback<"link" | "contain" | "paper" | "textField" | "bottomPaper">'.
    Type '{ textField: { minWidth: number; marginTop: number; }; contain: { margin: string; }; paper: { min...' is not assignable to type 'Record<"link" | "contain" | "paper" | "textField" | "bottomPaper", CSSProperties>'.
      Types of property 'paper' are incompatible.
        Type '{ minHeight: number; maxWidth: number; minWidth: number; textAlign: string; display: string; marg...' is not assignable to type 'CSSProperties'.
          Types of property 'textAlign' are incompatible.
            Type 'string' is not assignable to type '"left" | "right" | "center" | "start" | "end" | "inherit" | "initial" | "unset" | "justify" | "ma...'.

**Comment by Qolzam** [comment]
Thanks for reporting 👍. I have just updated the branch. I'm going to close issue. Let me know if any issue.
