### ISSUE TITLE
Cannot find module 'layouts/IconButtonElement'.

### ISSUE THREAD

**Issue by rohan-paul** [Qolzam/react-social-network#56]
I updated package.json to latest `"node": "10.1.0"`

Now after running ``npm start`` I am getting the below 

Failed to compile

```
/home/paul/PAUL/H/Web/R/R-Vid/2018/mern-stack-front-to-back-DEVELOPER-SOCIAL-NETWORK/OTHER-GIT-CLONED/react-social-network-110star/src/components/circle/CircleComponent.tsx
(24,31): Cannot find module 'layouts/IconButtonElement'.
This error occurred during the build time and cannot be dismissed.
```

**Comment by Qolzam** [comment]
Thanks for reporting. I have just [updated the package](https://github.com/Qolzam/react-social-network/commit/f1fb1a60786889908b28630aad58959dc01cd284) 8184eb0  please update your repository and try again. Let me know if any issue.

**Comment by rohan-paul** [comment]
Now I am getting 

```
Failed to compile
./src/components/comment/CommentComponent.tsx
Module not found: Can't resolve 'material-ui' in '/home/paul/PAUL/H/Web/R/R-Vid/2018/mern-stack-front-to-back-DEVELOPER-SOCIAL-NETWORK/OTHER-GIT-CLONED/react-social-network-110star-Problem/src/components/comment'
```

**Comment by Qolzam** [comment]
I guess you have not used `git pull` from repository to update your `local repository`. As I have upgrade `material-ui` to `@material-ui/core` you can't have `material-ui` as a reference any more. Please pull repository again and check if you can see `@material-ui/core` in `CommentComponent.tsx`. Thanks!

**Comment by rohan-paul** [comment]
I did a fresh git-clone of this repo and ran ``npm i`` and ``npm start`` and getting the below error again . My environment is Ubuntu 16.04

```
Failed to compile
/home/paul/PAUL/H/Web/R/R-Vid/2018/mern-stack-front-to-back-DEVELOPER-SOCIAL-NETWORK/OTHER-GIT-CLONED/react-social-network-110/src/components/circle/CircleComponent.tsx
(24,31): Cannot find module 'layouts/IconButtonElement'.
```

**Comment by Qolzam** [comment]
I have done 3 steps: 

``` bash
git clone git@github.com:Qolzam/react-social-network.git
yarn install or (npm install)
yarn start or (npm start) 
```

Everything seems well but I can't reproduce your issue. Please help to find if the file exist in layouts folder.

**Comment by Qolzam** [comment]
No reproduce. I'm going to close. Let me know if any issue.
