### ISSUE TITLE
Friends post appears in home page (but without his/ her profile image)

### ISSUE THREAD

**Issue by crappycocco** [Qolzam/react-social-network#71]
### Steps
Login, Follow user, Friends post appears in home page (but without profile image)
### Expected Result
Friends post should appear in home page with his / her profile image
### Actual Result
Friends post appears in home page, but without his / her profile image
### Version
1.0.0

### Testcase

**Comment by crappycocco** [comment]
@Qolzam

**Comment by Qolzam** [comment]
Thanks for reporting. Issue has been resolved. Please let me know if you any other issue. Thanks again!

**Comment by crappycocco** [comment]
@Qolzam thanks, will test and let you know
