### ISSUE TITLE
Facebook Share is not working

### ISSUE THREAD

**Issue by crappycocco** [Qolzam/react-social-network#72]
### Steps
Post, click on share button, popup opens, click 'Share in Facebook'
### Expected Result
FB Login prompt should open
### Actual Result
Sorry, something went wrong.
We're working on getting this fixed as soon as we can.
### Version
1.0.0

### Testcase

**Comment by crappycocco** [comment]
@Qolzam

**Comment by Qolzam** [comment]
Is it in production mode ?

**Comment by crappycocco** [comment]
In both modes

**Comment by crappycocco** [comment]
@Qolzam any updates on this, or is the react-share (2.2.0) broken?

**Comment by crappycocco** [comment]
@Qolzam , any updates?

**Comment by Qolzam** [comment]
Hope new change help you. Thanks!

**Comment by crappycocco** [comment]
@Qolzam - that worked, closing
