### ISSUE TITLE
[Security] Environment file is visible in both production and development

### ISSUE THREAD

**Issue by KaMeHb-UA** [Qolzam/react-social-network#77]
Is it normal that I can see my apiKey (both in production and in dev envs)? Is this not secret?
![deepinscreenshot_20180803101444](https://user-images.githubusercontent.com/20382677/43629542-33860f78-9706-11e8-811d-cfcbf2dfd118.png)
If it is normal, what rules need to be configured in firebase?
For my purpouses I need to generate secret access token for user and save it to firebase. But.. it will be readable for anyone with my apiKey, isn't it? So what can I do in this situation?

**Comment by Qolzam** [comment]
Thanks for reporting. Sure it's not normal. I will investigate in a few days. Please set a clear title to show the content. Thanks again!

**Comment by KaMeHb-UA** [comment]
Screen is provided from production build

**Comment by Qolzam** [comment]
Please pull new change and try again. Let me know if any issue. Thanks!

**Comment by KaMeHb-UA** [comment]
I've pulled your commit. But env files still exists in service worker. Then I've cleared both browser and service worker cache and it appeared in `/static/js/config` again

**Comment by KaMeHb-UA** [comment]
Yeah, of course!
I've done next:
1. Pulled latest commit from https://github.com/Qolzam/react-social-network.git `next`
2. Merged `next` with my own tree
3. Created production build with `yarn build`
4. Launched app with `serve -s build`
5. Looked to sources tab in Chrome Dev Tools
6. Seen only builded page
7. Looked to service worker files
8. Found env files
9. Cleared service worker resources with [Clear Service Worker extension](https://chrome.google.com/webstore/detail/clear-service-worker/kkbncldhbdallogkalmfgijpinjggboh)
10. Cleared browser cache in history tab
11. Reloaded page
12. Found env files in sources tab

**Comment by Qolzam** [comment]
Thanks a lot. Not sure why I see different but I found the reason. The source map files appear in Chrome so you can see all the source files. Here is the good [discussion](https://github.com/facebook/create-react-app/issues/1341) about this situation . So I am going to close this issue but let me know if any question. Thanks again!

**Comment by KaMeHb-UA** [comment]
So what to do? How about security? Base will be open for anyone?

**Comment by Qolzam** [comment]
Please read the [discussion](https://github.com/facebook/create-react-app/issues/1341) in details. there are enough solution for you to remove the source map files.

**Comment by KaMeHb-UA** [comment]
Yeah, I've read the discussion but forget to remove the comment. Thanks a lot!
